version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_NAME=Sistema de Seguro
      - APP_ENV=local
      - APP_KEY=base64:your-app-key-here
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=sistema_seguro
      - DB_USERNAME=root
      - DB_PASSWORD=password
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sistema_seguro
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: